### ISSUE TITLE
Error on PS5 FW1.00

### ISSUE THREAD

**Issue by MSZ-MGS** [john-tornblom/bdj-sdk#1]
On PS5 fw V1.00
![IMG_20220706_173904](https://user-images.githubusercontent.com/65172063/177775289-4536e03e-8830-4933-b898-a16b06d4f306.jpg)

**Comment by john-tornblom** [comment]
Interesting, perhaps fw 1.00 are still using an older jvm, in which case we can instantiate a class loader!

**Comment by john-tornblom** [comment]
Well, do not update to a more recent firmware, that is for sure. My suggestion is to learn a little bit of Java, and contribute with code. If that is not an option for you, and you have a spare ps5 at fw 1.00, you can send it to me and I'll make it work :D

**Comment by zecoxao** [comment]
i can confirm this error also shows up on my 6.72 testkit

**Comment by john-tornblom** [comment]
I do not have a ps5 at fw 1.00, but try latest master, it might work...
