### ISSUE TITLE
Again With This......

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [john-tornblom/bdj-sdk#12]
......And what I feared happened again, unable to compile as the program uses out of date packages.

Also, even though I Googled every package on the latest version, it gave this response:

<pre>sudo apt-get install libwxgtk3.2.1 -y libsdl2-dev -y libncurses6.4 -y liballegro5.2.8.0 tk8.6 -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libwxgtk3.2.1
E: Couldn&apos;t find any package by glob &apos;libwxgtk3.2.1&apos;
E: Couldn&apos;t find any package by regex &apos;libwxgtk3.2.1&apos;
E: Unable to locate package libncurses6.4
E: Couldn&apos;t find any package by glob &apos;libncurses6.4&apos;
E: Couldn&apos;t find any package by regex &apos;libncurses6.4&apos;
E: Unable to locate package liballegro5.2.8.0
E: Couldn&apos;t find any package by glob &apos;liballegro5.2.8.0&apos;
E: Couldn&apos;t find any package by regex &apos;liballegro5.2.8.0&apos;</pre>

**Comment by john-tornblom** [comment]
Not sure why you wanna install those packages, read the build instructions:
   https://github.com/john-tornblom/bdj-sdk#building
