### ISSUE TITLE
some errors while building bdj-sdk

### ISSUE THREAD

**Issue by zecoxao** [john-tornblom/bdj-sdk#2]
on the latest commit, i get this:
src/org/homebrew/PrivilegedFileIO.java:33: error: PrivilegedFileIO.PrivilegedImpl is not abstract and does not override abstract method mkdirs() in Interface
    class PrivilegedImpl extends FileFileIO implements Interface {
    ^
src/org/homebrew/PrivilegedFileIO.java:81: error: cannot find symbol
        return impl.getAbsolutePath();
                   ^
  symbol:   method getAbsolutePath()
  location: variable impl of type PrivilegedFileIO.PrivilegedImpl
src/org/homebrew/PrivilegedFileIO.java:85: error: cannot find symbol
        return impl.getCanonicalPath();
                   ^
  symbol:   method getCanonicalPath()
  location: variable impl of type PrivilegedFileIO.PrivilegedImpl
src/org/homebrew/PrivilegedFileIO.java:103: error: cannot find symbol
        return impl.getParent();
                   ^
  symbol:   method getParent()
  location: variable impl of type PrivilegedFileIO.PrivilegedImpl
4 errors
make: *** [Makefile:45: discdir/BDMV/JAR/00000.jar] Error 1

**Comment by zecoxao** [comment]
this is on the ps5filedump sample

**Comment by john-tornblom** [comment]
I belive this is fixed as of d99bd4d

**Comment by zecoxao** [comment]
ok, i'll check and let you know. thanks

**Comment by zecoxao** [comment]
confirmed working. however i have only tested this with jdk8, so i'll let someone else test with jdk11. closing...
