### ISSUE TITLE
Target/Makefile with new jdk8/jdk11

### ISSUE THREAD

**Issue by opoisso893** [john-tornblom/bdj-sdk#3]
The "bdj-sdk/taerget/Makefile" does not work because symbolic links are for jdk8 and jdk11.
Maybe, "JAVA_HOME    ?= $(BDJSDK_HOME)/host/jdk" should be modified.

using "JAVA_HOME    ?= $(BDJSDK_HOME)/host/jdk8" works 
but using "JAVA_HOME    ?= $(BDJSDK_HOME)/host/jdk11" gives a new error because source and target version 1.3 are not supported.
Maybe, "JFLAGS        := -Xlint:-options -source 1.3 -target 1.3" should also be modified.

**Comment by john-tornblom** [comment]
thanks, fixed in 1b3d4a2
