### ISSUE TITLE
Credits?

### ISSUE THREAD

**Issue by TheOfficialFloW** [john-tornblom/bdj-sdk#6]
.

**Comment by john-tornblom** [comment]
Thanks, for the pointer! Your issue description is somewhat vague, but I hope I have addressed it properly in the last couple of commits (5d587763, 38337161 etc). I will elaborate on the native execution sample when I get some time off from work (which will take a while). If you think I have gotten something wrong or left something out, please send a PR.

**Comment by john-tornblom** [comment]
I believe this issue is properly addressed as of 153a52458, closing.
