### ISSUE TITLE
Make Isn't Working...

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [john-tornblom/bdj-sdk#9]
``make: *** bdj/sdk/host/src/makefs_termux: No such file or directory. Stop.``

I think the above error says it all.

How do you fix this?

**Comment by De-Been-Tech-Solutions** [comment]
Ok, creating .iso's doesn't work either, same error, but on an actual Linux Distro.

**Comment by john-tornblom** [comment]
I'm guessing you missed the --recurse-submodules. Rerun the instructions from README.md again, and repoen this issue if this is still a problem

**Comment by De-Been-Tech-Solutions** [comment]
I even ran the recurse instruction, it replied with cannot create symbolic
link.

**Comment by De-Been-Tech-Solutions** [comment]
Johnny muh dood, there is a problem with your code, because it isn't us :).

Please see below:

VM is Kali Linux (a Debian based OS).

``sudo apt-get install build-essential libbsd-dev git pkg-config openjdk-8-jdk-headless openjdk-11-jdk-headless`` 

``[sudo] password for insertusernamehere:``
``Reading package lists... Done``
``Building dependency tree... Done``
``Reading state information... Done``
``E: Unable to locate package openjdk-8-jdk-headless``

The above means that Open JDK8 and even its headless package is no longer available.

The rest of them installed fine after removing ``openjdk-8-jdk-headless`` from the command, and ``git`` comes with all Linux operating systems.

Cloning your repository is perfectly fine, that doesn't fail, so getting your code is good.

Again, Open JDK 8 and its headless package is unavailable because its been removed from the repositories of all Debian based operating systems:

``ln -s /usr/lib/jvm/java-8-openjdk-amd64 bdj-sdk/host/jdk8``
``ln: failed to create symbolic link 'bdk-sdk/host/jdk8': No such file or directory``

This happens to JDK11 too:

``ln -s /usr/lib/jvm/java-11-openjdk-amd64 bdj-sdk/host/jdk11``
``ln: failed to create symbolic link 'bdk-sdk/host/jdk11': No such file or directory``

``make -C bdj-sdk/host/src/makefs_termux``
``make: *** bdj-sdk/host/src/makefs_termux: No such file or directory. Stop.``

The second make instruction returns this:

``make -C bdj-sdk/host/src/makefs_termux install DESTDIR=$PWD/bdj-sdk/host``
``make: *** bdj-sdk/host/src/makefs_termux: No such file or Directory. Stop.``

Make target is the same:

``make -C bdj-sdk/target``
``make: *** bdj-sdk/target: No such file or directory. Stop.``

So it isn't me, and most definitely not your community, its your code hands down.

You'll have to figure out a way around this.

**Comment by De-Been-Tech-Solutions** [comment]
You need to include double-quotations around the following commands in your README.md file in the first place for these commands to be able to work:

``ln -s "/usr/lib/jvm/java-8-openjdk-amd64 bdj-sdk/host/jdk8"``
``ln -s "/usr/lib/jvm/java-11-openjdk-amd64 bdj-sdk/host/jdk11"``

After input as above, instructions to the terminal worked.

**Comment by De-Been-Tech-Solutions** [comment]
Literally copying and pasting your listed commands does not work:

E.g.: ``make -C bdj-sdk/samples/helloworld``

``make: *** [Makefile:46: discdir/BDMV/JAR/00000.jar] Error 127``
